# SYSTEMS OF LINEAR EQUATIONS

## Gauss elimination method

In [365]:
import numpy as np

### Example systems of equations

$$\begin{bmatrix}
    2 & 7 & -1 & 3 & 1 \\
    2 & 3 & 4 & 1 & 7 \\
    6 & 2 & -3 & 2 & -1 \\
    2 & 1 & 2 & -1 & 2 \\
    3 & 4 & 1 & -2 & 1
\end{bmatrix}
\begin{bmatrix}
    x_1 \\
    x_2 \\
    x_3 \\
    x_4 \\
    x_5
\end{bmatrix}
=
\begin{bmatrix}
    5 \\
    7 \\
    2 \\
    3 \\
    4
\end{bmatrix}$$

#### simple example

$$\begin{bmatrix}
    0 & 7 & -1 & 3 & 1 \\
    2 & 3 & 4 & 1 & 7 \\
    6 & 2 & 0 & 2 & -1 \\
    2 & 1 & 2 & 0 & 2 \\
    3 & 4 & 1 & -2 & 1
\end{bmatrix}
\begin{bmatrix}
    y_1 \\
    y_2 \\
    y_3 \\
    y_4 \\
    y_5
\end{bmatrix}
=
\begin{bmatrix}
    5 \\
    7 \\
    2 \\
    3 \\
    4
\end{bmatrix}$$

#### simple example with zeros on diagonal

In [366]:
A = np.array([[2, 7, -1, 3, 1],
             [2, 3, 4, 1, 7],
             [6, 2, -3, 2, -1],
             [2, 1, 2, -1, 2],
             [3, 4, 1, -2, 1]], float)

B = np.array([[0, 7, -1, 3, 1],
             [2, 3, 4, 1, 7],
             [6, 2, 0, 2, -1],
             [2, 1, 2, 0, 2],
             [3, 4, 1, -2, 1]], float)

b = np.array([5, 7, 2, 3, 4], float)

c = np.array([5, 7, 2, 3, 4], float)

n = len(b)

x = np.zeros(n, float)

y = np.zeros(n, float)

In [367]:
A, B, b, c, x, y

(array([[ 2.,  7., -1.,  3.,  1.],
        [ 2.,  3.,  4.,  1.,  7.],
        [ 6.,  2., -3.,  2., -1.],
        [ 2.,  1.,  2., -1.,  2.],
        [ 3.,  4.,  1., -2.,  1.]]), array([[ 0.,  7., -1.,  3.,  1.],
        [ 2.,  3.,  4.,  1.,  7.],
        [ 6.,  2.,  0.,  2., -1.],
        [ 2.,  1.,  2.,  0.,  2.],
        [ 3.,  4.,  1., -2.,  1.]]), array([5., 7., 2., 3., 4.]), array([5., 7., 2., 3., 4.]), array([0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0.]))

### Elimination

In [368]:
for k in range(n-1):
    for i in range(k+1,n):
        multiplier = A[i,k]/A[k,k]
        b[i] -= multiplier*b[k] 
        for j in range(k,n):
            A[i,j] -= multiplier*A[k,j]

In [369]:
A, b

(array([[  2.        ,   7.        ,  -1.        ,   3.        ,
           1.        ],
        [  0.        ,  -4.        ,   5.        ,  -2.        ,
           6.        ],
        [  0.        ,   0.        , -23.75      ,   2.5       ,
         -32.5       ],
        [  0.        ,   0.        ,   0.        ,  -1.47368421,
          -1.84210526],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           2.25      ]]),
 array([  5.        ,   2.        , -22.5       ,  -0.73684211,
          0.5       ]))

In [370]:
for k in range(n-1):
    if B[k,k] == 0:
        for j in range(n):
            B[k,j], B[k+1,j] = B[k+1,j], B[k,j]
        c[k], c[k+1] = c[k+1], c[k]
    for i in range(k+1,n):
        if B[i,k] == 0: continue
        multiplier = B[i,k]/B[k,k]
        c[i] -= multiplier*c[k] 
        for j in range(k,n):
            B[i,j] -= multiplier*B[k,j]

In [371]:
B, c

(array([[  2.        ,   3.        ,   4.        ,   1.        ,
           7.        ],
        [  0.        ,   7.        ,  -1.        ,   3.        ,
           1.        ],
        [  0.        ,   0.        , -13.        ,   2.        ,
         -21.        ],
        [  0.        ,   0.        ,   0.        ,  -0.49450549,
          -1.02197802],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           7.16666667]]),
 array([  7.        ,   5.        , -14.        ,  -0.10989011,
          0.22222222]))

### Back-substitution

In [372]:
for i in reversed(range(0,n)):
    resolved_sum = 0
    for j in range(i+1,n):
        resolved_sum += A[i,j]*x[j]
    x[i] = (b[i] - resolved_sum)/A[i,i]

In [373]:
x

array([0.44444444, 0.55555556, 0.66666667, 0.22222222, 0.22222222])

In [374]:
for i in reversed(range(0,n)):
    resolved_sum = 0
    for j in range(i+1,n):
        resolved_sum += B[i,j]*y[j]
    y[i] = (c[i] - resolved_sum)/B[i,i]

In [375]:
y

array([0.02170543, 0.79224806, 1.05116279, 0.15813953, 0.03100775])

### Wrapping to a function

In [376]:
%%writefile gaussian_elimination.py

def find_row_with_max_value(matrix, column):
    maximal = max(matrix[column:,column])
    for i, value in enumerate(matrix[column:,column]):
        if value == maximal: return i+column
    else: return column

def swap_equations(index1, index2, matrix, vector):
    if index1 != index2:
        n = len(vector)
        for j in range(n):
            matrix[index1,j], matrix[index2,j] = matrix[index2,j], matrix[index1,j]
        vector[index1], vector[index2] = vector[index2], vector[index1]

def gauss_eliminate(matrix, vector):
    n = len(vector)
    for k in range(n-1):
        l = find_row_with_max_value(matrix,k)
        swap_equations(k,l,matrix,vector)
        for i in range(k+1,n):
            multiplier = matrix[i,k]/matrix[k,k]
            matrix[i,k] = 0.0
            vector[i] -= multiplier*vector[k]
            for j in range(k+1,n):
                matrix[i,j] -= multiplier*matrix[k,j];

def back_substitute(matrix, vector, answer):
    n = len(vector)
    for i in reversed(range(0,n)):
        resolved_sum = 0
        for j in range(i+1,n):
            resolved_sum += matrix[i,j]*answer[j]
        answer[i] = (vector[i] - resolved_sum)/matrix[i,i]
    return answer

def gaussian_elimination_solve(system_matrix, right_hand_sides):
    solution = np.zeros(len(right_hand_sides))
    gauss_eliminate(system_matrix, right_hand_sides)
    return system_matrix,back_substitute(system_matrix, right_hand_sides, solution)

Writing gaussian_elimination.py


In [377]:
A = np.array([[2, 7, -1, 3, 1],
             [2, 3, 4, 1, 7],
             [6, 2, -3, 2, -1],
             [2, 1, 2, -1, 2],
             [3, 4, 1, -2, 1]], float)

B = np.array([[0, 7, -1, 3, 1],
             [2, 3, 4, 1, 7],
             [6, 2, 0, 2, -1],
             [2, 1, 2, 0, 2],
             [3, 4, 1, -2, 1]], float)

b = np.array([5, 7, 2, 3, 4], float)

c = np.array([5, 7, 2, 3, 4], float)

In [378]:
gaussian_elimination_solve(A,b)

(array([[ 6.        ,  2.        , -3.        ,  2.        , -1.        ],
        [ 0.        ,  6.33333333,  0.        ,  2.33333333,  1.33333333],
        [ 0.        ,  0.        ,  5.        , -0.52631579,  6.84210526],
        [ 0.        ,  0.        ,  0.        , -1.47368421, -1.84210526],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  2.25      ]]),
 array([0.44444444, 0.55555556, 0.66666667, 0.22222222, 0.22222222]))

In [379]:
gaussian_elimination_solve(B,c)

(array([[ 6.        ,  2.        ,  0.        ,  2.        , -1.        ],
        [ 0.        ,  7.        , -1.        ,  3.        ,  1.        ],
        [ 0.        ,  0.        ,  4.33333333, -0.66666667,  7.        ],
        [ 0.        ,  0.        ,  0.        , -0.49450549, -1.02197802],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  7.16666667]]),
 array([0.02170543, 0.79224806, 1.05116279, 0.15813953, 0.03100775]))