# SYSTEMS OF LINEAR EQUATIONS

## Gauss elimination method

In [85]:
import numpy as np

### Example system of equations

$$\begin{bmatrix}
    2 & 7 & -1 & 3 & 1 \\
    2 & 3 & 4 & 1 & 7 \\
    6 & 2 & -3 & 2 & -1 \\
    2 & 1 & 2 & -1 & 2 \\
    3 & 4 & 1 & -2 & 1
\end{bmatrix}
\begin{bmatrix}
    x_1 \\
    x_2 \\
    x_3 \\
    x_4 \\
    x_5
\end{bmatrix}
=
\begin{bmatrix}
    5 \\
    7 \\
    2 \\
    3 \\
    4
\end{bmatrix}$$

In [86]:
A = np.array([[2, 7, -1, 3, 1],
             [2, 3, 4, 1, 7],
             [6, 2, -3, 2, -1],
             [2, 1, 2, -1, 2],
             [3, 4, 1, -2, 1]], float)

b = np.array([5, 7, 2, 3, 4])

n = len(b)

x = np.zeros(n, float)

In [87]:
A, b, x

(array([[ 2.,  7., -1.,  3.,  1.],
        [ 2.,  3.,  4.,  1.,  7.],
        [ 6.,  2., -3.,  2., -1.],
        [ 2.,  1.,  2., -1.,  2.],
        [ 3.,  4.,  1., -2.,  1.]]),
 array([5, 7, 2, 3, 4]),
 array([0., 0., 0., 0., 0.]))

### Elimination

In [88]:
for k in range(n-1):
    for i in range(k+1,n):
        multiplier = A[i,k]/A[k,k]
        b[i] -= multiplier*b[k] 
        for j in range(k,n):
            A[i,j] -= multiplier*A[k,j]

In [89]:
A, b

(array([[  2.        ,   7.        ,  -1.        ,   3.        ,
           1.        ],
        [  0.        ,  -4.        ,   5.        ,  -2.        ,
           6.        ],
        [  0.        ,   0.        , -23.75      ,   2.5       ,
         -32.5       ],
        [  0.        ,   0.        ,   0.        ,  -1.47368421,
          -1.84210526],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           2.25      ]]), array([  5,   2, -22,   0,   0]))

### Back-substitution

In [90]:
xn = b[n-1]/A[n-1,n-1]
xn

0.0